### ISSUE TITLE
Rolling d0s

### ISSUE THREAD

**Issue by Synopt** [ArtemGr/Sidekick#12]
If you `/roll 1d0` on Sidekick, the answer is always 1.

If you `/roll 1d0` on Roll20, the answer is always 0.

I don't rightly know why anyone might want to roll a d0, but since it's a valid input, I was wondering if there was a reason for this discrepancy?

**Comment by ArtemGr** [comment]
Good catch, I think the proper answer is 0.

And the reason for the difference is that Sidekick doesn't use roll20 in any way, it's a separate codebase  =

**Comment by arcandio** [comment]
Could also arise through some series of modifiers or something as well.

I do wonder why a d0 would come up as a 1, thought. A die with no sides? Shouldn't the result in theory be 0 anyway? The [Dice Reference](https://wiki.roll20.net/Dice_Reference) only mentions it once, seemingly for no reason.

**Comment by ArtemGr** [comment]
> I do wonder why a d0 would come up as a 1, thought. A die with no sides?

In case of the Sidekick bot it's a technical issue. The random number generator gives me the number between 0 and 1. That's what they usually do. To get the number in a given range we multiply by the range size, e.g. `$r * 10` would be a number between 0 and 10. But to roll d10 we don't need a number between 0 and 10, we need a number between 1 and 10. So what I do is multiply by 9 and then add 1.

1d0 rolls to one because of that later +1.

**Comment by arcandio** [comment]
Oh, oops, I had my wires crossed, and thought Roll20 was rolling `d0` as `1`. I get it now. Derp.

**Comment by ArtemGr** [comment]
1d0 fixed to be 0.
