### ISSUE TITLE
[Bug] Strikethrough formatting oddities

### ISSUE THREAD

**Issue by yascherki** [ArtemGr/Sidekick#230]
Not sure if this is a Sidekick or Discord bug, but the double tilde strikethrough markers sometimes don't get parsed as such - or only one double tilde of the pair gets parsed, making the strikethough escape onto other text:
![Screen Shot 2020-02-26 at 8 36 58 PM](https://user-images.githubusercontent.com/10777102/75412932-f2541b80-58d8-11ea-8d6d-5e17f55b10d2.png)

**Comment by ArtemGr** [comment]
That's actually a Discord bug.
For example, for `/r 4d2d1r1k3` I can get `(~~1~~+2+~~1~~_+1_+~~1~~_+2_) = 5` from Discord but I know for a fact that it's not what the bot has sent.
There is some new heuristic in Discord that re-processes the bot's output and screws it for us.

To address this I'm experimenting with adding a space between the numbers.

**Comment by ArtemGr** [comment]
So simply adding a space between the numbers didn't help.

Adding the spaces to strikeout specifically:
```
        write! (&mut text, "{plus}{strikeoutⁱ}{rolled}{strikeoutₒ}",
          strikeoutⁱ = if roll.counts {""} else {" ~~"},
          strikeoutₒ = if roll.counts {""} else {"~~ "},
```
seems to be helping. Tell me if it works for you.

**Comment by yascherki** [comment]
Sorry, meant to reply and forgot.  That does seem like it fixed the glitchy strikeouts - I haven't seen any that failed to get parsed or overflowed after the fix.  There is a minor cosmetic side effect from the different spacing around strikeouts vs. normal rolls:

![Screen Shot 2020-03-26 at 10 47 28 AM](https://user-images.githubusercontent.com/10777102/77679588-fb73ef00-6f4f-11ea-9138-f725cb04bc66.png)

But that doesn't get in the way of reading the results the way the original issue did.  Thanks for the fix. =)

**Comment by ArtemGr** [comment]
You're welcome!

Yeah, that new formatting is kind of unfortunate, but we have some different combinations of formatting and to properly test them against this new formatting bug in Discord we'd need to maybe test them differently, like employing an actual Discord application to be a side in the test, sending the generated texts there and verifying that the HTML generated by Discord is one we expect.

Or maybe we'd find a different way to format, like with the image attachments.

Or maybe we'd revamp the formatting into something layered due to having new UIs besides the Discord.

So it's possible we'll get back to that.
