### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by JackMaxwell123** [ArtemGr/Sidekick#238]
Sidekick is being delayed by several minutes, it's making dnd very hard since we have to wait several minutes between roll results. This is the nest dice bot on discord so I would really apreciate a restart ❤ thanks.

**Comment by mysterycycle** [comment]
I'm having the same problem. We're in the middle of a game with eight players right now, so a restart would be greatly appreciated. Thanks!

**Comment by ArtemGr** [comment]
Discord slowdowns are unlikely to be caused by the bot.
More likely that the self-isolation puts a strain on Discord infrastructure.
cf. https://github.com/ArtemGr/Sidekick/issues/232#issuecomment-605665671
I'm willing to experiment and restart a shard whenever there is a slowdown, to see if it helps, but this should be happening via IM in order to have fast message round-trips and feedback. For that, you can join https://discord.gg/yAWa8Qj and hail artemciy_dice there.

**Comment by goathelmet** [comment]
I am seeing the bot offline for over 15 min now on my server.  
![3FEEF9C9-5BA5-4029-8E06-52B20DD2AAA9](https://user-images.githubusercontent.com/64236761/80164689-ad322a00-85a7-11ea-909b-9d97b8c99e4e.png)
![44E96B6B-776C-49B4-AD5D-94CC67BD96F0](https://user-images.githubusercontent.com/64236761/80164690-ad322a00-85a7-11ea-84cc-54c05cf3e009.png)
