### ISSUE TITLE
Sidekick Offline

### ISSUE THREAD

**Issue by LouizT7** [ArtemGr/Sidekick#270]
The other day, I came to my server and Sidekick was offline, Even though at other servers he was on, It's been days already and he didn't come back, What happened ? 
![z0TN9QYDjgFX](https://user-images.githubusercontent.com/74368452/98961734-ab4c9b80-24e4-11eb-993b-be1c2527df5e.png)

**Comment by rvaessen** [comment]
I am having the same problem. Problem was first noted (for me) on the 14th of Nov, 2020. I kicked the bot, and rejoined it to my server, but it went offline less than 24 hours later, and it's been offline ever since. I just kicked it off my server five minutes ago. After inviting sidekick, I greeted him (said 'hi!' w/direct message) but it's still offline.

**Comment by rvaessen** [comment]
Alright - Another update. Very odd things happening on Discord. Several friends dropped off completely, no long visible as Offline; including Sidekick. I deleted Sidekick from my server, then re-invited him (again), I got a response that said 'Authorized', but he's not visible (not online of offline). I quit Discord and restarted it, but that didn't help. I quit Discord, tried authorizing Sidekick again, received confirmation (green check mark 'Authorized'), restarted Discord, but he's still not visible in the members list. As a matter of fact, another bot (Dice Maiden) is also missing from my members list (I didn't kick it, it just vanished)... Very strange activity (at ~0300 mountain time).

**Comment by ArtemGr** [comment]
I usually cringe when I see people re-authorizing the bot, because architecturally my guess would be that bot authorization and message delivery are entirely different subsystems. We didn't have any evidence so far that the authorization in Discord is getting lost.

As for the disconnected shards, yeah, that's a problem we're working on:

![image](https://user-images.githubusercontent.com/41847/99527332-ad639e00-29ad-11eb-8432-6307f503ca52.png)

**Comment by rvaessen** [comment]
Just got back from work ~0600 until ~1530 mountain time. I started Discord, but I still don't see Sidekick in my list of friends/joined to my server. The authorization must have gotten lost. I'll try Authorizing the bot again...

I quit Discord, then navigated to this link: <https://discordapp.com/oauth2/authorize?&client_id=209040908673482753&scope=bot&permissions=0> The Discord authorization dialog (for sidekick) appeared, I selected my server 'RobsWorld!', then clicked 'Authorize'. I got the 'Authorized' notification (see screen capture), 
![sidekickauthorized_18nov2020](https://user-images.githubusercontent.com/425786/99597702-9fb21680-29b5-11eb-91b7-634241b7f35f.png) After authorization indicated, I restarted Discord (on my iMac running macOS Catalina (version 10.15.7 (19H15)). Approximately ~1528MST and there's still no Discord in the list of users joined to the server (see screen capture) or friends. I can't direct message or command Sidekick...
![whoshere_18nov2020](https://user-images.githubusercontent.com/425786/99598908-8f02a000-29b7-11eb-94a8-fce1e43cbd4c.png)

I checked again at ~1530MST, and now Sidekick appears as joined to the server (still not listed in friends), but the bot is still 'Offline'. I was able to Direct Message the bot from there, and the command worked (I rolled a d10 and got a result), then the bot showed up in my list of friends.

I tried issuing a "/r 1d10" command in the 'general-ingame' channel (under TEXT CHANNELS category), but Sidekick won't respond to that, and it's still 'Offline' (at appx ~1559MST). Notably, Dice Maiden was also missing from Server and friends list, but it's back in both; awake/active/online on the server.

**Comment by rvaessen** [comment]
I'm still having the same problem. I've been unable to use Sidekick since the 14th of Nov. I've restarted Discord, kicked Sidekick, reauthorized sidekick, all multiple times with negative results. Sidekick is present on my server, but the bot is offline, and I can't seem to make it wake up. I can send it direct messages, and it answers (rolls dice), but it's not listening to any of the channels where it has permissions.

**Comment by rvaessen** [comment]
### SideKick is Back! #

I got up this morning at 0300MST, and discovered that my computer was offline. Apparently XFinity was addressing some unspecified, unplanned outage. According to my logs, the outage lasted from ~0001 - 0349MST.  Just as I was about to head downstairs for a workout, I fired up Discord to check on the Sidekick bot - Guess What! Sidekick is Awake, and responding to commands on my server. So that was a six day outage for me... I hope LuizT7, originator of this thread is also seeing a living breathing Sidekick as well. I think I'll leave my server on Region West for now. No reason to change that now that Sidekick is back up and running. Thanks to all those who worked to restore Sidekick's vitality. **Long live Sidekick!**

**Comment by kiloforce** [comment]
Seems to be offline again.

**Comment by ArtemGr** [comment]
Ouch. I'm experimenting with using the `remaining` field in https://discord.com/developers/docs/topics/gateway#get-gateway-bot, but it's jumpy, we're loosing connectivity before we go out of `remaining`. Will try with slowing down dead shard reconnects at a longer disntance

**Comment by kiloforce** [comment]
Back online.  Thanks!

**Comment by zdwolfe** [comment]
Also seeing the same behavior of Sidekick being stuck offline.

**Comment by ArtemGr** [comment]
Update: https://github.com/ArtemGr/Sidekick/issues/232#issuecomment-740244912

**Comment by Dreit-Rc** [comment]
Hi, I also have a problem with the Sidekick bot, it went offline. Last night it worked fine, and stammatina went offline. What is happening to the bot?
Yours sincerely.

**Comment by Dreit-Rc** [comment]
The Sidekick bot is working beautifully on my server this morning. Thank you for fixing it. I don't know to others how it's going. If something happens we will notify you.
Yours sincerely.

**Comment by ArtemGr** [comment]
Thanks, @Dreit-Rc ! Not fixed yet, but linked above was a comment pointing to the videos that describe where we are with this: https://youtu.be/9sZJSVfRogo (30 minutes), https://youtu.be/Z-ZXbMIBmwo (13 minutes)

**Comment by Dreit-Rc** [comment]
Thank you. Sir.


Il giorno mer 9 dic 2020 alle ore 12:25 Artem <notifications@github.com> ha
scritto:

**Comment by ArtemGr** [comment]
Closed in favor of #232, please follow up there
