### ISSUE TITLE
[Suggestion] Option to create Server Saved Rolls

### ISSUE THREAD

**Issue by psychoza** [ArtemGr/Sidekick#56]
I have a defined roll to create attributes for a D&D character:

`/r $att = repeat(4d6kh3, 6)`

After doing so, I was able to successfully call `/r $att` but other users were not able to. They had to define their own roll. Now each user who wants to have the same roll function are filling up the saved rolls with all of the same commands.

It would be nice to have server based saved rolls that all users had access to without re-defining them.

**Comment by ArtemGr** [comment]
Hi, @psychoza!

Any idea on how we ought to approach this?

I see several options:

1) `/r share ($att)` - a special command to share the memorized roll.
2) All rolls are shared, `/r $att` tries to get the user's roll first, and if the user hasn't defined $att then it picks the latest $att defined on the server.
3) Maybe like (2) but search in the channel first.

Any other options?

**Comment by Tarliman** [comment]
I like option 1, which would allow picking and choosing what is shared 
out, and allow us to share what we already have built.


On 07/03/2017 09:40 AM, Artem wrote:
>
>  1. |/r share ($att)| - a special command to share the memorized roll.
>  2. All rolls are shared, |/r $att| tries to get the user's roll
>     first, and if the user hasn't defined $att then it picks the
>     latest $att defined on the server.
>  3. Maybe like (2) but search in the channel first.
>

-- 
Andrew W. Ragland
andrew.ragland@gmail.com

**Comment by psychoza** [comment]
Hard choices! Of the choices I think the easiest to handle, especially if a bunch of people already have their saved rolls setup, would be option #1, a special command to share specific saved rolls.

**Comment by Tarliman** [comment]
Also, the sharing should be restricted to the channel, so that you don't 
run out of unique short names.

While you're at it, a way of listing the saved rolls would be useful.


On 07/03/2017 11:24 AM, Jesse Hutchison wrote:
> Hard choices! Of the choices I think the easiest to handle, especially 
> if a bunch of people already have their saved rolls setup, would be 
> option #1 <https://github.com/ArtemGr/Sidekick/issues/1>, a special 
> command to share specific saved rolls.

-- 
Andrew W. Ragland
andrew.ragland@gmail.com

**Comment by ArtemGr** [comment]
> While you're at it, a way of listing the saved rolls would be useful.

You can do it with `/r $` now.

**Comment by ArtemGr** [comment]
I wonder about the conflicts.

Suppose we have user A having a roll $foo memorized.
Now user B wants to share the same roll. User A will stick with her version of the roll, wouldn't she?

And what if user A wants to share the $foo as well?

Also I'm considering a different syntax for making a shared roll,
```
/r $ATT = repeat(4d6kh3, 6)
```

The difference is in the case. Most major computer languages I know of converge at a style guideline of using the caps for the global variables. I'm thinking of making it a part of the syntax: if the variable is all caps then it's shared, if it isn't all caps then it's local to the user.

There's also an idea to make the shared variables being owned by the channel or the server rather than the user. Thus we attack the problem of conflicts on two sides: 1) shared variables are always distinct from the local ones ($ATT is always shared, it can not be local, similarly $att is always local to the user, it can not be shared); 2) there's only one version of the shared variable, the one which belongs to the channel / server.

**Comment by ArtemGr** [comment]
Okay, I think it's working now. For example:
![screenshot](http://i.imgur.com/6HRfgNX.png)

When we memorize an all-caps roll, it now belongs to the channel and not to the user. Any user can use it or update it inside that channel.

**Comment by BKTidswell** [comment]
Hello,
Is there any way to make this per server and not per channel? I would prefer not to have to retype each line of the 20 saved roles on multiple servers. Being able to save all the rolls in one combined script would also work.
Ben
