### ISSUE TITLE
[issue] 7minute delay, any ideas how to reset/restart

### ISSUE THREAD

**Issue by pitbull008** [ArtemGr/Sidekick#59]
Hey! Not sure why my discord is slow, i checked another discord server that has the same bot but i currently have a 7 minute delay. Any ideas? Pitbull#9132 for furtehr info!

I tried to remove the bot from the server and re-add it, worked for a second then delay. I even changed my discord server from USEast to USCentral but no change.

**Comment by pitbull008** [comment]
Looks like issue resolved, very very odd.

**Comment by ArtemGr** [comment]
Interesting.
I have restarted the bot, maybe it'll help.

**Comment by pitbull008** [comment]
Fixed for now, will update in a couple hours and see if its still working or if lagging. Is this an acceptable method to communicate about it?

**Comment by ArtemGr** [comment]
Of course!

**Comment by pitbull008** [comment]
Thanks, love the bot! I run a 40~ person 5e discord PBP server. It's been the only bot we use! We have another but i prefer yours. Thanks for the time to code it. I will consider donating soon~

**Comment by ArtemGr** [comment]
Glad to hear it!

> I will consider donating soon

Donating one or two dollars hardly makes any difference to you, but if more servers where sponsoring the bot that way it would've made a huge difference to the bot. It terms of reliability as well, because the High Availability setup [I've made earlier](https://www.patreon.com/posts/bots-on-high-and-8325144) is no longer supported by Discord and redesigning the bot to [another approach](https://stackoverflow.com/a/43643283/257568) would take a lot of time.

**Comment by pitbull008** [comment]
Looks like a huge delay again, not sure how or why. I have not had problems since you restarted it. Also on another discord server i see no errors at all. Any idea?

**Comment by ArtemGr** [comment]
Right now I've been restarting the bot in order to roll out the new feature (`/r $`). During restarts downtime is currently expected (you can read more at https://stackoverflow.com/a/43643283/257568, in option 4; Discord no longer supports the High Availability approach that I've initially implemented, so we're down to one server where restarting the shards one by one takes a bit of a time).

**Comment by pitbull008** [comment]
No worries, thanks for responding. I will close this out as it seems to be working just fine

**Comment by ArtemGr** [comment]
I'm glad to hear that!

**Comment by ArtemGr** [comment]
cf. #129
